### ISSUE TITLE
input监听到输入但无法正确录入内容

### ISSUE THREAD

**Issue by wjzhang-ty** [SNFocus/approvalFlow#10]
在定制表单的页面，添加一些输入框并录入一些值。然后点开浏览。反复一两次input就无法录入任何内容了。但是却可以监听到表单事件。这个是什么情况？

**Comment by SNFocus** [comment]
抱歉 我尝试了数次没有复现该问题，可能是render的实现有问题，下次复现时我会积极去解决，非常感谢您的提醒。

**Comment by wjzhang-ty** [comment]
再最近两次的提交中已经解决了这个问题，我clone的版本略久。非常感谢大佬
