### ISSUE TITLE
表单内容很多的时候 编辑table时出现bug

### ISSUE THREAD

**Issue by davy-gan** [SNFocus/approvalFlow#11]
表单预览页面删除table栏 鼠标移动的时候删除弹框会跳走
![Kapture 2020-08-31 at 17 16 12](https://user-images.githubusercontent.com/21240946/91704269-f88bc300-ebad-11ea-80f3-68b67397eac5.gif)

**Comment by SNFocus** [comment]
抱歉，我尝试复现您遇到的状况，但没有成功。
看图片感觉可能是某个组件触发了重新渲染。
如果方便的话您可以提供您操作的步骤，或者我会再尝试一段时间，复现该BUG会积极修复。
感谢回复。

**Comment by davy-gan** [comment]
基本是100%复现的 就是把那个删除的弹框调出来后 将鼠标移到旁边滚动一下窗口 ，然后在每次移动出去鼠标 就会出现

**Comment by SNFocus** [comment]
感谢指正，目前已修复。
