### ISSUE TITLE
在任意一个流程环节下，连续添加三个条件（同一个添加按钮）就会出现Bug

### ISSUE THREAD

**Issue by ShallowGreen** [SNFocus/approvalFlow#14]
Bug复现一：例如在一个发起人环节下面的 **添加按钮**，连续添加三次条件环节，会出现严重bug
Bug复现二：在相邻的两个条件环节中间的 **添加按钮**，添加条件环节，会出现严重Bug

应该是` static appendBranch(data, isBottomBtnOfBranch) ` 该函数少处理某些操作

如果能修复，非常感谢

**Comment by SNFocus** [comment]
现在应该修复了  感谢指正

**Comment by ShallowGreen** [comment]
> 现在应该修复了 感谢指正

Bug复现一：例如在一个发起人环节下面的 添加按钮，连续添加三次条件环节，目前节点不会紊乱，但是删除的时候会报错，具体哪一个报错好像是不定的，先加三个，试试把加上去的三个条件节点都删除，会复现。
报错内容：`vue.esm.js:1897 TypeError: Cannot read property 'findIndex' of undefined`

**Comment by SNFocus** [comment]
删除无反应应该已经修复了，多条件分支删除报错目前未能复现。
感谢您的问题反馈。

**Comment by ShallowGreen** [comment]
Bug复现： 添加连续两个条件节点，在下面这个条件节点添加一个新的条件判断，再删除新增的这个条件判断，会导致整个节点的消失

**Comment by ShallowGreen** [comment]
非常感谢解决

**Comment by SNFocus** [comment]
感谢反馈 您再看看有没有问题😂😂😂

**Comment by ShallowGreen** [comment]
> 感谢反馈 您再看看有没有问题

233333，我谢谢您才是，整个项目解决了一个大需求，哈哈哈
赞!!!
