### ISSUE TITLE
添加两个以上条件节点时，第二个条件节点设置条件出错

### ISSUE THREAD

**Issue by Vimalate** [SNFocus/approvalFlow#15]
页面情况：
![](https://gitee.com/lj107571/imgformd/raw/master/Snipaste_2020-10-15_11-28-46.png)
错误信息：
![image](https://user-images.githubusercontent.com/47288962/96073176-83afe680-0ed8-11eb-8587-29f10c9535c3.png)

应该是util.js 里的 getPreviousNode（）方法判断有些情况没考虑到

**Comment by SNFocus** [comment]
感谢您的反馈，不过我测试多次未能找到正确的复现步骤。但是我尝试过程中找到可可能导致出错的原因：id重复，并完成了新的提交。
希望这次提交能有所改善。

**Comment by Vimalate** [comment]
是的，感谢大佬，现在错误已解决
