### ISSUE TITLE
在条件分支中取消了发起人条件保存后，再次打开条件的弹窗发起人条件还是会出现在条件中

### ISSUE THREAD

**Issue by zxmlx** [SNFocus/approvalFlow#18]
![image](https://user-images.githubusercontent.com/24725166/99946016-a1fae300-2db0-11eb-88b7-942dbb6316f1.png)
![image](https://user-images.githubusercontent.com/24725166/99946028-a58e6a00-2db0-11eb-8eb1-ab854a648d50.png)
![image](https://user-images.githubusercontent.com/24725166/99946031-a8895a80-2db0-11eb-97bb-836e2306ee04.png)
取消了发起人的勾选，弹窗关闭后，下次打开发起人条件仍在

**Comment by SNFocus** [comment]
1. 发起人默认存在 右边没有删除按钮 
2. 每次重新打开抽离都会重置条件显示状态 发起人一定显示  其他条件只显示含有信息的 和勾选框无关
3. 勾选框只在抽屉显示时生效，抽屉关闭后会重置
感谢反馈

**Comment by zxmlx** [comment]
谢谢，我了解了。感谢开源
