### ISSUE TITLE
提个小建议，能否给每个input控件都添加个宽度调整

### ISSUE THREAD

**Issue by landonzeng** [SNFocus/approvalFlow#5]
非常感谢分享，正好公司工作流开发这里用得到，能否默认所有input控件的宽度都一样，金额和数字的input比文本框短了好多，有点难看 :D

**Comment by landonzeng** [comment]
时间控件这也还可以优化一下
![QQ截图20200624114350](https://user-images.githubusercontent.com/7336781/85497369-621cad80-b610-11ea-9598-beeb5fe4c2fc.png)

**Comment by SNFocus** [comment]
感谢建议。数字/金额已添加组件长度属性，若想和其他控件长度保持一致可以配置该属性。

**Comment by landonzeng** [comment]
非常感谢
