### ISSUE TITLE
请问有交流群吗？

### ISSUE THREAD

**Issue by yanghaifeng88** [SNFocus/approvalFlow#6]
群主有QQ或微信吗？加一下交流

**Comment by SNFocus** [comment]
很遗憾  并没有交流群 。毕竟这个项目这个项目很一般 ， 表单设计也是照搬大佬的项目，最主要的我还是个渣新。

**Comment by yanghaifeng88** [comment]
这项目做得蛮不错的，最近在做审批流项目正好用上，请问这个项目支持移动端H5吗？

**Comment by SNFocus** [comment]
谢谢夸奖。项目不支持移动端。

**Comment by yanghaifeng88** [comment]
如果要支持移动端要重新适配？

**Comment by SNFocus** [comment]
嗯  我个人觉得这个审批流程配置其实配置项挺多的 用作移动端可能操作方面没有PC方便吧
如果只是单纯想展示配置后的表单  直接使用项目中的渲染页面就行(移动端使用单列布局会好很多) 我觉得应该还是可行的

**Comment by yanghaifeng88** [comment]
PC端做审批流配置，移动端做申请，审批。移动端肯定是单行展示的，但是移动端有些控件的展示与PC端的会有不同，例如：日期，多选这类的。

**Comment by SNFocus** [comment]
项目用的是ElementUI 要想有移动端的体验恐怕是很难了 找vant之类的移动端框架重写一个渲染页面可能更好些吧

**Comment by hhzhldhjl** [comment]
挺不错的，我不是做前端的，我们有个项目是html普通项目，不知道有没有什么好办法能整合到一起

**Comment by SNFocus** [comment]
恕我才疏学浅，没有想到什么好办法

**Comment by SNFocus** [comment]
非常抱歉，我也没有什么好的想法。

**Comment by jasonwish** [comment]
我也是希望渲染界面在移动端有一个比较好的体验，无论如何，这个审批都非常棒
