### ISSUE TITLE
审批流程，右侧抽屉修改数据如何保存

### ISSUE THREAD

**Issue by ysyniko** [SNFocus/approvalFlow#9]
您好，我想请问一下，审批流程修改完数据之后是在哪一步保存，更新视图的，我看了好久，onPropEditConfirm也没写如何更新更改后的数据，然后传了data进去，但是也是在保存之后更新的，能否说明一下，谢谢

**Comment by SNFocus** [comment]
onPropEditConfirm中 最后一步调用了this.forceUpdate()方法 希望对您有帮助

**Comment by ysyniko** [comment]
是在PropPanel里直接修改了processData吗，然后再掉forceUpdate更新视图吗

**Comment by SNFocus** [comment]
PropPanel里维护的应该是当前节点的properties副本，点击确定按钮后，传递修改后的数据并调用onPropEditConfirm，覆盖原有数据（应该是这一步修改了processData）,最后调用this.forceUpdate()强制更新视图

**Comment by ysyniko** [comment]
懂了懂了，非常感谢

**Comment by SNFocus** [comment]
communication
